# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zane < Formula
  desc "Conversational Kubernetes co-pilot in your terminal"
  homepage "https://github.com/zarakM/zane"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zarakM/zane/releases/download/v0.1.3/zane_0.1.3_Darwin_x86_64.tar.gz"
      sha256 "d4879fb2eef9fc1bd8918c8c1aad028ff3423b5bbf3e47775f989305492e0265"

      define_method(:install) do
        bin.install "zane"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zarakM/zane/releases/download/v0.1.3/zane_0.1.3_Darwin_arm64.tar.gz"
      sha256 "683314b33a1ed2a899b964b7756730d81f9fce824ec0b7cbacd3cb8dc657383d"

      define_method(:install) do
        bin.install "zane"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarakM/zane/releases/download/v0.1.3/zane_0.1.3_Linux_x86_64.tar.gz"
      sha256 "e3a9951107a643798022bbff3d0064154b17b66c78d4321c892340b9a7fd1aeb"
      define_method(:install) do
        bin.install "zane"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarakM/zane/releases/download/v0.1.3/zane_0.1.3_Linux_arm64.tar.gz"
      sha256 "a70f20240728d7f05407a4de13d321e9d0c7d38474c23fc62218aff341dc981b"
      define_method(:install) do
        bin.install "zane"
      end
    end
  end

  def caveats
    <<~EOS
      zane needs an Anthropic API key (ANTHROPIC_API_KEY env var or the
      first-run wizard) and a kubeconfig (KUBECONFIG or ~/.kube/config).
      Start the co-pilot by running: zane
    EOS
  end
end
