# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zane < Formula
  desc "Conversational Kubernetes co-pilot in your terminal"
  homepage "https://github.com/zarakM/zanecli"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zarakM/zanecli/releases/download/v0.1.2/zane_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "0ad422296c9056c8d76b3c535d0682375870fea3c2f2dc045451162fd85756bd"

      define_method(:install) do
        bin.install "zane"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zarakM/zanecli/releases/download/v0.1.2/zane_0.1.2_Darwin_arm64.tar.gz"
      sha256 "ecdc7f126f7e1bcb08fc08fd04e37935123c791286fc002d5cdf1f9f7da55c59"

      define_method(:install) do
        bin.install "zane"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarakM/zanecli/releases/download/v0.1.2/zane_0.1.2_Linux_x86_64.tar.gz"
      sha256 "bc89b2ed80ef823b2f9178331e58c0e942ebd3a99dc7119d3e9c19d839a304a4"
      define_method(:install) do
        bin.install "zane"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarakM/zanecli/releases/download/v0.1.2/zane_0.1.2_Linux_arm64.tar.gz"
      sha256 "cd7487257a53893a56ca220b9cd3628d38446a49d5d875c0beda83cd8fc6f096"
      define_method(:install) do
        bin.install "zane"
      end
    end
  end

  def caveats
    <<~EOS
      zane needs an Anthropic API key (ANTHROPIC_API_KEY env var or the
      first-run wizard) and a kubeconfig (KUBECONFIG or ~/.kube/config).
      Start the co-pilot by running: zane
    EOS
  end
end
