# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zane < Formula
  desc "Conversational Kubernetes co-pilot in your terminal"
  homepage "https://github.com/zarakM/zane"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zarakM/zane/releases/download/v0.1.4/zane_0.1.4_Darwin_x86_64.tar.gz"
      sha256 "918e1459cd327bc01168add289251ae7080a1f91020a9144e9d8a69eb2ae94bc"

      define_method(:install) do
        bin.install "zane"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zarakM/zane/releases/download/v0.1.4/zane_0.1.4_Darwin_arm64.tar.gz"
      sha256 "3cd3242e8febb284707bc7d709ff6a76d1fae3123d07ec2e4d6354e3f5c2fe93"

      define_method(:install) do
        bin.install "zane"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarakM/zane/releases/download/v0.1.4/zane_0.1.4_Linux_x86_64.tar.gz"
      sha256 "85cb0f8bedbc22c5b722a734c2c60f8b595db69a9213527b25affd29ad9eb2aa"
      define_method(:install) do
        bin.install "zane"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarakM/zane/releases/download/v0.1.4/zane_0.1.4_Linux_arm64.tar.gz"
      sha256 "80037de5fa1a2fd11ed813e32e4f0a5ef1cb39eead657ad9386599a431186242"
      define_method(:install) do
        bin.install "zane"
      end
    end
  end

  def caveats
    <<~EOS
      zane needs an Anthropic API key (ANTHROPIC_API_KEY env var or the
      first-run wizard) and a kubeconfig (KUBECONFIG or ~/.kube/config).
      Start the co-pilot by running: zane
    EOS
  end
end
