# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zanecli < Formula
  desc "Conversational Kubernetes co-pilot in your terminal"
  homepage "https://github.com/zarakM/zanecli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zarakM/zanecli/releases/download/v0.1.1/zanecli_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "bceecfbad7df6d5325ebae2a687d0b2c961f08ce5983af3ae4e613b03225303f"

      define_method(:install) do
        bin.install "zanecli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zarakM/zanecli/releases/download/v0.1.1/zanecli_0.1.1_Darwin_arm64.tar.gz"
      sha256 "293f2532365501474bad632cfa791188054011517fc40b1926e63b8513687295"

      define_method(:install) do
        bin.install "zanecli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarakM/zanecli/releases/download/v0.1.1/zanecli_0.1.1_Linux_x86_64.tar.gz"
      sha256 "b74e82a92b529c0575aa87b2b60a152096d1c8f1a7c4ba878b8b789ebb7a6ebc"
      define_method(:install) do
        bin.install "zanecli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarakM/zanecli/releases/download/v0.1.1/zanecli_0.1.1_Linux_arm64.tar.gz"
      sha256 "bbfefd9a5378fbad17b9633308e72a66b060c6b2f5c999c34fa9609a403cb1f6"
      define_method(:install) do
        bin.install "zanecli"
      end
    end
  end

  def caveats
    <<~EOS
      zanecli needs an Anthropic API key (ANTHROPIC_API_KEY env var or the
      first-run wizard) and a kubeconfig (KUBECONFIG or ~/.kube/config).
      Start the co-pilot by running: zanecli
    EOS
  end
end
